### ISSUE TITLE
Max results per pages are 1000. We are in need of a bit more. 

### ISSUE THREAD

**Issue by luiscape** [reubano/HDX-Age-API#4]
When making queries to the API using the parameter `results_per_page` Flask RESTless uses that to override the default number of results (which is 10). However, if the parameter `max_results_per_page` is not modified, the results will be capped at its maximum, which is 1000. 

I am trying to make the following request:
- http://www.hdxdatateam.xyz/api/dataset_age/age?results_per_page=3000

But only getting 1000 results back. Would it be possible to change that parameter to about 3000? It's not the best of solutions, but at least we would be able to see all the datasets in the dashboard.

Here's a piece of their documentation: http://flask-restless.readthedocs.org/en/latest/customizing.html#server-side-pagination

**Comment by reubano** [comment]
You can set the max results setting in config.py to achieve what u want.
